<a href="https://colab.research.google.com/github/abhishekjindal724/T20_score_predictor/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pickle
import numpy as np

In [ ]:
df = pickle.load(open('dataset_level2.pkl','rb'))

In [ ]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8671
venue                  0
dtype: int64

In [ ]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: count, dtype: int64

In [ ]:
cities = np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [ ]:
df['city'] = cities

In [ ]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [ ]:
df.drop(columns=['venue'],inplace=True)

In [ ]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
119,3,Bangladesh,India,0.1,0,0,Rajkot
120,3,Bangladesh,India,0.2,1,0,Rajkot
121,3,Bangladesh,India,0.3,0,0,Rajkot
122,3,Bangladesh,India,0.4,1,0,Rajkot
123,3,Bangladesh,India,0.5,0,0,Rajkot
...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg
116323,962,Australia,South Africa,19.3,2,0,Johannesburg
116324,962,Australia,South Africa,19.4,1,0,Johannesburg
116325,962,Australia,South Africa,19.5,1,0,Johannesburg
116326,962,Australia,South Africa,19.6,4,0,Johannesburg

In [ ]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()
df = df[df['city'].isin(eligible_cities)]
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
365,5,New Zealand,England,0.1,0,0,Wellington
366,5,New Zealand,England,0.2,0,0,Wellington
367,5,New Zealand,England,0.3,0,0,Wellington
368,5,New Zealand,England,0.4,1,0,Wellington
369,5,New Zealand,England,0.5,1,0,Wellington
...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg
116323,962,Australia,South Africa,19.3,2,0,Johannesburg
116324,962,Australia,South Africa,19.4,1,0,Johannesburg
116325,962,Australia,South Africa,19.5,1,0,Johannesburg
116326,962,Australia,South Africa,19.6,4,0,Johannesburg

In [ ]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

<ipython-input-12-ceeb700eb00c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [ ]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
365,5,New Zealand,England,0.1,0,0,Wellington,0
366,5,New Zealand,England,0.2,0,0,Wellington,0
367,5,New Zealand,England,0.3,0,0,Wellington,0
368,5,New Zealand,England,0.4,1,0,Wellington,1
369,5,New Zealand,England,0.5,1,0,Wellington,2
...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg,188
116323,962,Australia,South Africa,19.3,2,0,Johannesburg,190
116324,962,Australia,South Africa,19.4,1,0,Johannesburg,191
116325,962,Australia,South Africa,19.5,1,0,Johannesburg,192
116326,962,Australia,South Africa,19.6,4,0,Johannesburg,196

In [ ]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

<ipython-input-14-4fd5a57c1fcd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
<ipython-input-14-4fd5a57c1fcd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5
...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg,188,19,2
116323,962,Australia,South Africa,19.3,2,0,Johannesburg,190,19,3
116324,962,Australia,South Africa,19.4,1,0,Johannesburg,191,19,4
116325,962,Australia,South Africa,19.5,1,0,Johannesburg,192,19,5
116326,962,Australia,South Africa,19.6,4,0,Johannesburg,196,19,6

In [ ]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')
df

<ipython-input-15-e7d17f656852>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1,1
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2,2
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3,3
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4,4
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg,188,19,2,116
116323,962,Australia,South Africa,19.3,2,0,Johannesburg,190,19,3,117
116324,962,Australia,South Africa,19.4,1,0,Johannesburg,191,19,4,118
116325,962,Australia,South Africa,19.5,1,0,Johannesburg,192,19,5,119
116326,962,Australia,South Africa,19.6,4,0,Johannesburg,196,19,6,120

In [ ]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

<ipython-input-16-7ed065e8960c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - df['balls_bowled']
<ipython-input-16-7ed065e8960c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1,1,119
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2,2,118
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3,3,117
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4,4,116
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,0,Johannesburg,188,19,2,116,4
116323,962,Australia,South Africa,19.3,2,0,Johannesburg,190,19,3,117,3
116324,962,Australia,South Africa,19.4,1,0,Johannesburg,191,19,4,118,2
116325,962,Australia,South Africa,19.5,1,0,Johannesburg,192,19,5,119,1
116326,962,Australia,South Africa,19.6,4,0,Johannesburg,196,19,6,120,0

In [ ]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
df['player_dismissed'] = df['player_dismissed'].astype('int')
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()
df['wickets_left'] = 10 - df['player_dismissed']

<ipython-input-17-b54fded4d398>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
<ipython-input-17-b54fded4d398>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].astype('int')
<ipython-input-17-b54fded4d398>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()
<ipython-input-17-b54fded4d398>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left'] = 10 - df['player_dismissed']

In [ ]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1,1,119,10
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2,2,118,10
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3,3,117,10
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4,4,116,10
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,6,Johannesburg,188,19,2,116,4,4
116323,962,Australia,South Africa,19.3,2,6,Johannesburg,190,19,3,117,3,4
116324,962,Australia,South Africa,19.4,1,6,Johannesburg,191,19,4,118,2,4
116325,962,Australia,South Africa,19.5,1,6,Johannesburg,192,19,5,119,1,4
116326,962,Australia,South Africa,19.6,4,6,Johannesburg,196,19,6,120,0,4

In [ ]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

<ipython-input-19-fad47fc85776>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [ ]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1,1,119,10,0.000000
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2,2,118,10,0.000000
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3,3,117,10,0.000000
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4,4,116,10,1.500000
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5,5,115,10,2.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,6,Johannesburg,188,19,2,116,4,4,9.724138
116323,962,Australia,South Africa,19.3,2,6,Johannesburg,190,19,3,117,3,4,9.743590
116324,962,Australia,South Africa,19.4,1,6,Johannesburg,191,19,4,118,2,4,9.711864
116325,962,Australia,South Africa,19.5,1,6,Johannesburg,192,19,5,119,1,4,9.680672
116326,962,Australia,South Africa,19.6,4,6,Johannesburg,196,19,6,120,0,4,9.800000

In [ ]:
groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []
for id in match_ids:
    last_five.extend(groups.get_group(id).rolling(window=30)['runs'].sum().values.tolist())

In [ ]:
df['last_five'] = last_five

<ipython-input-23-83d24d575aa4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = last_five

In [ ]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
365,5,New Zealand,England,0.1,0,0,Wellington,0,0,1,1,119,10,0.000000,NaN
366,5,New Zealand,England,0.2,0,0,Wellington,0,0,2,2,118,10,0.000000,NaN
367,5,New Zealand,England,0.3,0,0,Wellington,0,0,3,3,117,10,0.000000,NaN
368,5,New Zealand,England,0.4,1,0,Wellington,1,0,4,4,116,10,1.500000,NaN
369,5,New Zealand,England,0.5,1,0,Wellington,2,0,5,5,115,10,2.400000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116322,962,Australia,South Africa,19.2,6,6,Johannesburg,188,19,2,116,4,4,9.724138,46.0
116323,962,Australia,South Africa,19.3,2,6,Johannesburg,190,19,3,117,3,4,9.743590,44.0
116324,962,Australia,South Africa,19.4,1,6,Johannesburg,191,19,4,118,2,4,9.711864,44.0
116325,962,Australia,South Africa,19.5,1,6,Johannesburg,192,19,5,119,1,4,9.680672,44.0
116326,962,Australia,South Africa,19.6,4,6,Johannesburg,196,19,6,120,0,4,9.800000,44.0

In [ ]:
final_df = df.groupby('match_id')['runs'].sum().reset_index().merge(df,on='match_id')

In [ ]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [ ]:
final_df.dropna(inplace=True)
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [ ]:
final_df = final_df.sample(final_df.shape[0]) #shuffling

In [ ]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
3476,Australia,England,Sydney,93,73,9,11.872340,71.0
20582,Bangladesh,Pakistan,Pallekele,74,71,8,9.061224,39.0
5123,India,South Africa,Durban,53,61,7,5.389831,20.0
17350,Pakistan,England,Cardiff,50,76,8,6.818182,34.0
7047,Australia,Pakistan,Johannesburg,79,69,8,9.294118,47.0
...,...,...,...,...,...,...,...,...
13225,New Zealand,Sri Lanka,Colombo,151,16,7,8.711538,43.0
6271,South Africa,England,Cape Town,95,28,4,6.195652,22.0
50501,India,Bangladesh,Delhi,54,68,8,6.230769,33.0
16138,Pakistan,England,Barbados,87,45,6,6.960000,29.0
24318,West Indies,Australia,Colombo,114,35,8,8.047059,44.0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [ ]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [ ]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [ ]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

0.988147747376306
1.6471221661286044

In [ ]:
pickle.dump(pipe,open('pipe.pkl','wb'))

In [ ]:
from google.colab import files
files.download('pipe.pkl')